DROP TABLE IF EXISTS user;
CREATE TABLE user (
	id BIGINT NOT NULL AUTO_INCREMENT, 
	username VARCHAR(20) NOT NULL DEFAULT '', 
	password VARCHAR(20) NOT NULL DEFAULT '',  
	birthday DATE DEFAULT NULL,
	PRIMARY KEY (id)
);